# Generated by Django 3.1.7 on 2022-05-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220501_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
