# Generated by Django 3.1.7 on 2022-02-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0002_auto_20220120_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='provider',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='historicalexpense',
            old_name='provider',
            new_name='supplier',
        ),
    ]
