# Generated by Django 3.1.7 on 2022-02-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0003_auto_20220211_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplier',
            name='business_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='business_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Razón Social'),
        ),
    ]
